var lang_data = {
    zh_CN:{
        title: "缅甸佛塔监测系统",
        menu: ["缅甸佛塔监测系统","监测数据","统计报表","监测报警"],
        user: '用户名',
        username: '用户',
        password: '密码',
        login: '登录',
        logout: '退出',
        input_user: '请输入用户名',
        input_pwd: '请输入密码',
        msg_no_login: '没有登录或登录超时,请登录',
        confirm: '确&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;认',
        login_right: '登录成功',
        login_wrong: '用户名或密码错误',
        network_wrong: '请检查您的网络',
        exit_s: '退出成功',
        D: "静力水准仪",
        C: "裂缝计",
        A: "倾角计",
        unit: "单位",
        month: '月',
        day: '日',
        download: '下载',
        no_data: "暂无数据",
        loading: "数据加载中...",
        start_time: '开始时间',
        end_time: '结束时间',
        layer_lang: 'zh',
        btn_generating: '生成报表',
        btn_down: '下载报表',
    },
    en_US:{
        title: "Pagoda Monitoring System",
        //menu: ["Myanmar Pagoda Monitoring System","Monitoring","Statement","Alarming"],
        menu: ["Pagoda System","Monitoring","Statement","Alarming"],
        user: 'User',
        username: 'Username',
        login: 'Login',
        password: 'Password',
        logout: 'Logout',
        input_user: 'Enter one user name',
        input_pwd: 'Please input a password',
        msg_no_login: 'No login or timeout, please login',
        confirm: 'Confirm',
        login_right: 'Successful login',
        login_wrong: 'ERROR Incorrect username or password',
        network_wrong: 'Please check your network',
        exit_s: 'Successful exit',
        D: "Static level",
        C: "Crack gauge",
        A: "Inclinometer",
        unit: "Unit",
        month: 'Month',
        day: 'Day',
        download: 'Download',
        no_data: "No data available for the time being",
        loading: "Data loading...",
        start_time: 'Start time',
        end_time: 'End time',
        layer_lang: 'en',
        btn_generating: 'Generating Report',
        btn_down: 'Download Report',
    },

    //my_BU
    my_BU:{
        title: "မြန်မာစေတီတော်စောင့်ကြည့်ရေးစနစ်က",
        menu: ["စောင့်ကြည့်မှုစနစ်","စောငျ့ရှောကျ","အစီရင်ခံစာပုံစံ","သတိပေးခြင်း"],
        user: 'အသုံးပြုသူ',
        username: 'အသုံးပြုသူ',
        password: 'စကားဝှက်ကို',
        login: 'လော့ဂ်အင်',
        logout: 'ထွက်သွား',
        input_user: 'တဦးတည်းရဲ့ အသုံးပြုသူကိုရိုက်ထည့်',
        input_pwd: 'ရေးသားစကားဝှက်ကို',
        msg_no_login: 'ရဲ့ login သို့မဟုတ်ရဲ့ login အချိန်ကုန်ဘယ်သူမျှမက, သွားရောက်ကြည့်ရှုကျေးဇူးပြုပြီး',
        confirm: 'အတည်ပြု',
        login_right: 'အောင်မြင်သော',
        login_wrong: 'အသုံးပြုသ ဒါမှမဟုတ် စကားဝှက်က ကိုမမှန်ကန်',
        network_wrong: 'သင့်ရဲ့ကွန်ယက်ကိုစစ်ဆေးပါ',
        exit_s: 'ကိုအောင်မြင်',
        D: "စေ့စပ်ခြင်းပစ္စည်းကရိယာ",
        C: "ရိုက်သံပစ္စည်းကရိယာ",
        A: "ယိုင်ခြင်းပစ္စည်းကရိယာ",
        unit: "ယူနစ်",
        month: 'လ',
        day: 'နေ့',
        download: 'ဒေါင်းလုပ်',
        no_data: "အဘယ်သူမျှမဒေတာ",
        loading: "ပေါ်သယ်ဆောင်...",
        start_time: 'အစပြုကိုအချိန်',
        end_time: 'အဆုံးကိုအချိန်',
        layer_lang: 'en',
        btn_generating: 'အစီရင်ခံစာများ ',
        btn_down: 'ဒေါင်းလုပ',
    },

}