var lang_data = {
    zh_CN:{
        title: "缅甸佛塔监测系统",
        menu: ["缅甸佛塔监测系统","监测数据","统计报表","监测报警"],
        user: '用户名: ',
        //user: '',
        username: '用户',
        password: '密码',
        login: '登录',
        logout: '退出',
        input_user: '请输入用户名',
        input_pwd: '请输入密码',
        msg_no_login: '没有登录或登录超时,请登录',
        confirm: '确&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;认',
        login_right: '登录成功',
        login_wrong: '用户名或密码错误',
        network_wrong: '请检查您的网络',
        exit_s: '退出成功',
        D: "静力水准仪",
        C: "裂缝计",
        A: "倾角计",
        unit: "单位",
        month: '月',
        day: '日',
        download: '下载',
        no_data: "暂无数据",
        loading: "数据加载中...",
        start_time: '开始时间',
        end_time: '结束时间',
        input_start_time:'请输入开始时间',
        input_end_time:'请输入结束时间',
        layer_lang: 'zh',
        btn_generating: '生成报表',
        btn_down: '下载报表',
        ta1_name: '葛道帕林寺',
        ta2_name: '瑞山都塔',
        word:{
            jingtu:'深圳中科天巡信息技术有限公司',
            word_1_title:'缅甸蒲甘佛塔安全监测',
            word_1_title_f:'监测报告',
            word_title1:'一、工程概况',
            word_1_text:
            '    缅甸蒲甘，是缅甸历史古城、佛教文化遗址、著名旅游胜地，位于国境中部，坐落在伊洛瓦底河中游左岸。位于流经缅甸中央之伊洛瓦底江中游，为缅族之中心地区。\n' +
            '    佛塔之都，曾经的448.6万多座佛塔和寺院赐予了这里"万塔之城"的美誉。虽然经历沧桑岁月900多年，历史变迁和地震灾害已使它的昔日辉煌不再，但今天仍保留着的约2000座大小佛塔和佛教遗迹，吸引着来自四面八方的游人。\n' +
            '    根据卫星数据和水文数据等初步分析，拟选15处佛塔为候选监测对象。现场实地踏勘考察新蒲甘、旧蒲甘、伊洛瓦底江流向、人居用水、建设开采、人员在佛塔的活动（旅游）等因素，建议选择葛道帕林寺（Gawdawpalin Temple）和瑞山都寺（Shewsandaw Pagoda）作为监测目标。',
            p1_text:'图1-1 踏勘轨迹和选点对象',
            p1_text2:'图1-2 大裂缝和区域沉降',
            p1_text3:'图1-3 东面裂缝',
            p1_text4:'图1-4 南面裂缝',
            p1_text5:'图1-5 北面裂缝',
            p1_text6:'图1-6 西面裂缝',
            p1_text7:'图1-7 内部裂缝',
            p1_text8:'图1-8 区域沉降',
            p1_text9:'图1-9 瑞山都寺北面入口',
            p1_text10:'图1-10北面贯穿大裂缝',
            p1_text11:'图1-11 东面大裂缝',
            p1_text12:'图1-12 西面贯穿大裂缝',
            p1_text13:'图1-13 南面裂缝裂缝',
            word_title2:'二、现状与踏勘',
            word_2_text:'    （1）据现场踏勘，葛道帕林寺现状如下：\n' +
            '    位于伊洛瓦底江东侧，直线距离很近，地表沙化较严重，附近有两处人流量较大酒店，平常游客较多，受自然因素和人类活动影响较大。\n' +
            '    初步判断受地下水开采和地震影响较大，塔身每一个正面和不同高层立面和水平面均有很多长裂缝，佛塔内部也有水平、竖立面和非特定方向大裂缝，塔体处于不均匀沉降区域内，佛塔四周地面存在较多长裂缝，塔身已存在明显差异沉降，需对其全面监测，以分析其变形成因和趋势。',
            word_3_text:'    （2）据现场踏勘，瑞山都塔现状如下：\n' +
            '    位于蒲甘老城腹地，地表沙化较严重，平常游客较多，佛塔由土砖堆建而成，更多受自然因素（地震）影响较大。\n' +
            '    考察判断受地震影响较大，塔身每一个正面的所有窗户衔接处均有很多长裂缝，佛塔内部也有水平、竖立面方向大裂缝，塔体高处承重柱有多处长裂缝，塔身西面高层侧面有明显倾斜，与下午太阳西晒有一定关系，需对其全面监测，以分析其变形成因和趋势。',
            word_4_text:'    勘察结论：\n' +
            '    (1) 需要对葛道帕林寺不均匀沉降使用静力水准仪进行实时监测，分析区域沉降状态。\n' +
            '    (2)需要对葛道帕林寺和瑞山都寺的倾斜使用倾角传感器进行实时监测。\n' +
            '    (3)需要对葛道帕林寺和瑞山都寺的裂缝使用裂缝计进行实时监测。',
            word_title3:'三、监测结论',
            b1_text1:'表3-1 葛道帕林寺监测内容统计表',
            b1_text2:'表3-2 瑞山都塔监测内容统计表',
            word_title4:'四、监测数据成果',
            word_title4_1:'各测点累计变形值随时间变化曲线',
            p4_1:'图 4-1 葛道帕林寺倾角监测点累计变形值随时间变化曲线图',
            p4_2:'图 4-1 瑞山都塔倾角监测点累计变形值随时间变化曲线图',
            p4_3:'图 4-1 葛道帕林寺塔裂缝测点累计变形值随时间变化曲线图',
            p4_4:'图 4-1 瑞山都塔塔裂缝测点累计变形值随时间变化曲线图',
            p4_5:'图 4-1 葛道帕林寺差异沉降监测点累计变形值随时间变化曲线图',
            word_title5:'五、测点布设图',
            p5_1:'图5-1 葛道帕林寺传感器布设图',
            p5_2:'图5-2 瑞山都佛塔传感器布设图',
            word_A: '倾斜',
            word_C: '裂缝',
            word_D: '差异沉降',
            table1: '监测项目',
            table2: '变化值最大测点',
            table3: '变化值最大测点变化值',
            table4: '累计变形值最大测点',
            table5: '累计变形值最大值',
            table6: '变化速率',
            table7: '备注',

        },

        alarm: '监测预警',
        number_: '序号',
        why: '报警原因',
        handle: '报警处置',
        plan : '处置方案',
        alarm_time: '报警时间',
        operation: '操作',

    },
    en_US:{
        title: "Pagoda Monitoring System",
        //menu: ["Myanmar Pagoda Monitoring System","Monitoring","Statement","Alarming"],
        menu: ["Pagoda System","Monitoring","Statement","Alarming"],
        user: 'User: ',
        //user: '',
        username: 'Username',
        login: 'Login',
        password: 'Password',
        logout: 'Logout',
        input_user: 'Enter one user name',
        input_pwd: 'Please input a password',
        msg_no_login: 'No login or timeout, please login',
        confirm: 'Confirm',
        login_right: 'Successful login',
        login_wrong: 'ERROR Incorrect username or password',
        network_wrong: 'Please check your network',
        exit_s: 'Successful exit',
        D: "Static level",
        C: "Crack gauge",
        A: "Inclinometer",
        unit: "Unit",
        month: 'Month',
        day: 'Day',
        download: 'Download',
        no_data: "No data available for the time being",
        loading: "Data loading...",
        start_time: 'Start time',
        end_time: 'End time',
        input_start_time:'Please enter the start time',
        input_end_time:'Please enter the end time',
        layer_lang: 'en',
        btn_generating: 'Generating Report',
        btn_down: 'Download Report',
        ta1_name: 'GAW.DAW.PALIN.PHAYA',
        ta2_name: 'SHWE SAN DAW PAGODA',

        word:{
            jingtu:'Shenzhen Zhongke Tianxun Information Technology Co., Ltd.',
            word_1_title:'Security Monitoring of Puganfo Pagoda in Myanmar',
            word_1_title_f:'Monitoring Report',
            word_title1:'I. General Situation of Engineering',
            word_1_text:'Pugan, Myanmar, is a historic city, Buddhist cultural site and famous tourist attraction in Myanmar. It is located in the central part of the border and on the left bank of the middle reaches of the Irrawaddy River. Located in the middle reaches of the Irrawaddy River flowing through the central part of Myanmar, it is the central area of the Myanmar people.\n' +
            'The city of pagodas, which used to have more than 4.486 million pagodas and monasteries, has given it the reputation of "the city of ten thousand pagodas".  Although it has gone through more than 900 years of vicissitudes, historical changes and earthquake disasters have made its past glorious no longer, but today it still retains about 2000 large and small Buddhist pagodas and Buddhist relics, attracting tourists from all directions.\n' +
            'According to the preliminary analysis of satellite data and hydrological data, 15 pagodas are proposed to be selected as candidate monitoring objects. On-the-spot investigation of the new Pugan, the old Pugan, the flow direction of the Irrawaddy River, water consumption for human settlements, construction and mining, activities of people in Buddhist pagodas (tourism) and other factors suggests that Gawdaw Palin Temple and Shewsandaw Pagoda be selected as monitoring targets.',
            p1_text:'Figure 1-1 Reconnaissance Trajectory and Point Selection Objects',
            p1_text2:'Figure1-2 Large fissures and regional subsidence',
            p1_text3:'Figure1-3 Eastern crack',
            p1_text4:'Figure1-4 Southern crack',
            p1_text5:'Figure1-5 North crack',
            p1_text6:'Figure1-6 Western fissure',
            p1_text7:'Figure1-7 Internal cracks',
            p1_text8:'Figure1-8 Regional subsidence',
            p1_text9:'Figure1-9 North entrance of Ruishan Du Temple',
            p1_text10:'Figure1-10 Large fissures run through the North',
            p1_text11:'Figure1-11 Great Eastern Crack',
            p1_text12:'Figure1-12 Large fissures penetrate the West',
            p1_text13:'Figure1-13 Southern crack',
            word_title2:'II. Present Situation and Survey',
            word_2_text:'(1) According to the site survey, the present situation of the Goldoparin Temple is as follows:\n' +
            'Located in the eastern side of the Irrawaddy River, the straight line is very close, and the desertification of the surface is serious. There are two Hotels with large human flow nearby. There are more tourists, and they are greatly influenced by natural factors and human activities.\n' +
            'Preliminary judgment is greatly influenced by groundwater exploitation and earthquakes. There are many long cracks in each front and different high-rise elevations and horizontal planes of the tower body. There are also large cracks in horizontal, vertical and non-specific directions in the interior of the tower. The tower body is in the area of uneven settlement. There are many long cracks in the ground around the tower, and the tower body has been clearly visible. The obvious differential settlement needs to be monitored comprehensively in order to analyze its deformation causes and trends.',
            word_3_text:'(2) According to the site survey, the present situation of Ruishan Duta is as follows:\n' +
            'Located in the hinterland of the old city of Pugan, the surface desertification is serious, and there are more tourists. The pagoda is built of earth bricks, which is more affected by natural factors (earthquakes).\n' +
            'The investigation and judgment are greatly affected by the earthquake. There are many long cracks at the joints of all windows on each front of the tower body. There are also large horizontal and vertical cracks in the interior of the pagoda. There are many long cracks in the load-bearing column at the height of the tower body. The high-rise side of the West side of the tower body is obviously inclined, which is related to the sunshine in the afternoon. Monitoring is used to analyze the cause and trend of deformation.',
            word_4_text:'Survey conclusions:\n' +
            '(1) It is necessary to use static level to monitor the uneven settlement of Goldoparin Temple in real time and analyze the regional settlement state.\n' +
            '(2) It is necessary to monitor the inclination of Goldoparin Temple and Ruishandu Temple by using inclination sensor in real time.\n' +
            '(3) It is necessary to monitor the cracks in the Gedao Palin Temple and Ruishan Du Temple in real time by using the crack gauge.',
            word_title3:'III. CONCLUSION OF MONITORING',
            b1_text1:'Table 3-1 Statistical Table of Monitoring Contents of the Golden Palin Temple',
            b1_text2:'Table 3-2 Statistical Table of Monitoring Content of Ruishan Duta',
            word_title4:'IV. Monitoring Data Achievements',
            word_title4_1:'Curve of cumulative deformation with time at each measuring point',
            p4_1:'Figure 4-1 Curve Chart of Cumulative Deformation with Time at Obliquity Monitoring Points of Golden Palin Temple',
            p4_2:'Figure 4-1 Curve Chart of Accumulated Deformation of Duta Inclination Monitoring Point in Ruishan with Time',
            p4_3:'Figure 4-1 Curve Chart of Accumulated Deformation of Crack Measurement Points at Golden Palin Temple Tower with Time',
            p4_4:'Figure 4-1 Curve Chart of Accumulated Deformation with Time at Crack Measuring Points of Duta Tower, Ruishan',
            p4_5:'Figure 4-1 Curve Chart of Accumulated Deformation of Differential Settlement Monitoring Points at Goldoparin Temple with Time',
            word_title5:'V. Layout of Surveying Points',
            p5_1:'Fig. 5-1 Sensor Layout of Golden Palin Temple',
            p5_2:'Fig. 5-2 Sensor Layout of Dufo Tower in Ruishan',
            word_A: 'Inclination sensor',
            word_C: 'Crack',
            word_D: 'Differential settlement',
            table1: 'Monitoring projects',
            table2: 'Max Devname',
            table3: 'Max Value',
            table4: 'Accumulative MaxDevname',
            table5: 'Accumulative MaxValue',
            table6: 'ChangeRate',
            table7: 'Remarks',

        },

        alarm: 'Monitoring and Early Warning',
        number_: 'Number',
        why: 'Cause of alarm',
        handle: 'Alarm disposal',
        plan : 'Disposal plan',
        alarm_time: 'Alarm time',
        operation: 'Operation',
    },

    //my_BU
    my_MM:{
        title: "Pagoda Monitoring Systemမြန်မာစေတီတော်စောင့်ကြည့်ရေးစနစ်က",
        menu: ["စောင့်ကြည့်မှုစနစ်","စောငျ့ရှောကျ","အစီရင်ခံစာပုံစံ","သတိပေးခြင်း"],
        user: 'အသုံးပြုသူ: ',
        //user: '',
        username: 'အသုံးပြုသူ',
        password: 'စကားဝှက်ကို',
        login: 'လော့ဂ်အင်',
        logout: 'ထွက်သွား',
        input_user: 'တဦးတည်းရဲ့ အသုံးပြုသူကိုရိုက်ထည့်',
        input_pwd: 'ရေးသားစကားဝှက်ကို',
        msg_no_login: 'ရဲ့ login သို့မဟုတ်ရဲ့ login အချိန်ကုန်ဘယ်သူမျှမက, သွားရောက်ကြည့်ရှုကျေးဇူးပြုပြီး',
        confirm: 'အတည်ပြု',
        login_right: 'အောင်မြင်သော',
        login_wrong: 'အသုံးပြုသ ဒါမှမဟုတ် စကားဝှက်က ကိုမမှန်ကန်',
        network_wrong: 'သင့်ရဲ့ကွန်ယက်ကိုစစ်ဆေးပါ',
        exit_s: 'ကိုအောင်မြင်',
        D: "စေ့စပ်ခြင်းပစ္စည်းကရိယာ",
        C: "ရိုက်သံပစ္စည်းကရိယာ",
        A: "ယိုင်ခြင်းပစ္စည်းကရိယာ",
        unit: "ယူနစ်",
        month: 'လ',
        day: 'နေ့',
        download: 'ဒေါင်းလုပ်',
        no_data: "အဘယ်သူမျှမဒေတာ",
        loading: "ပေါ်သယ်ဆောင်...",
        start_time: 'အစပြုကိုအချိန်',
        end_time: 'အဆုံးကိုအချိန်',
        input_start_time:'စတင်ချိန်ရိုက်ထည့်ပေးပါ',
        input_end_time:'အဆုံးအချိန်ကိုရိုက်ထည့်ပေးပါ',
        layer_lang: 'en',
        btn_generating: 'အစီရင်ခံစာများ ',
        btn_down: 'ဒေါင်းလုပ',
        ta1_name: 'လမ်းမကြီး ဘုရားကျောင်း',
        ta2_name: 'ဆွစ်ဇာလန်တောင်များမျှော်စင်',

        word:{
            jingtu:'Shenzhen Zhongke Tianxun Information Technology Co., Ltd.',
            word_1_title:'Security Monitoring of Puganfo Pagoda in Myanmar',
            word_1_title_f:'Monitoring Report',
            word_title1:'I. General Situation of Engineering',
            word_1_text:'Pugan, Myanmar, is a historic city, Buddhist cultural site and famous tourist attraction in Myanmar. It is located in the central part of the border and on the left bank of the middle reaches of the Irrawaddy River. Located in the middle reaches of the Irrawaddy River flowing through the central part of Myanmar, it is the central area of the Myanmar people.\n' +
            'The city of pagodas, which used to have more than 4.486 million pagodas and monasteries, has given it the reputation of "the city of ten thousand pagodas".  Although it has gone through more than 900 years of vicissitudes, historical changes and earthquake disasters have made its past glorious no longer, but today it still retains about 2000 large and small Buddhist pagodas and Buddhist relics, attracting tourists from all directions.\n' +
            'According to the preliminary analysis of satellite data and hydrological data, 15 pagodas are proposed to be selected as candidate monitoring objects. On-the-spot investigation of the new Pugan, the old Pugan, the flow direction of the Irrawaddy River, water consumption for human settlements, construction and mining, activities of people in Buddhist pagodas (tourism) and other factors suggests that Gawdaw Palin Temple and Shewsandaw Pagoda be selected as monitoring targets.',
            p1_text:'Figure 1-1 Reconnaissance Trajectory and Point Selection Objects',
            p1_text2:'Figure1-2 Large fissures and regional subsidence',
            p1_text3:'Figure1-3 Eastern crack',
            p1_text4:'Figure1-4 Southern crack',
            p1_text5:'Figure1-5 North crack',
            p1_text6:'Figure1-6 Western fissure',
            p1_text7:'Figure1-7 Internal cracks',
            p1_text8:'Figure1-8 Regional subsidence',
            p1_text9:'Figure1-9 North entrance of Ruishan Du Temple',
            p1_text10:'Figure1-10 Large fissures run through the North',
            p1_text11:'Figure1-11 Great Eastern Crack',
            p1_text12:'Figure1-12 Large fissures penetrate the West',
            p1_text13:'Figure1-13 Southern crack',
            word_title2:'II. Present Situation and Survey',
            word_2_text:'(1) According to the site survey, the present situation of the Goldoparin Temple is as follows:\n' +
            'Located in the eastern side of the Irrawaddy River, the straight line is very close, and the desertification of the surface is serious. There are two Hotels with large human flow nearby. There are more tourists, and they are greatly influenced by natural factors and human activities.\n' +
            'Preliminary judgment is greatly influenced by groundwater exploitation and earthquakes. There are many long cracks in each front and different high-rise elevations and horizontal planes of the tower body. There are also large cracks in horizontal, vertical and non-specific directions in the interior of the tower. The tower body is in the area of uneven settlement. There are many long cracks in the ground around the tower, and the tower body has been clearly visible. The obvious differential settlement needs to be monitored comprehensively in order to analyze its deformation causes and trends.',
            word_3_text:'(2) According to the site survey, the present situation of Ruishan Duta is as follows:\n' +
            'Located in the hinterland of the old city of Pugan, the surface desertification is serious, and there are more tourists. The pagoda is built of earth bricks, which is more affected by natural factors (earthquakes).\n' +
            'The investigation and judgment are greatly affected by the earthquake. There are many long cracks at the joints of all windows on each front of the tower body. There are also large horizontal and vertical cracks in the interior of the pagoda. There are many long cracks in the load-bearing column at the height of the tower body. The high-rise side of the West side of the tower body is obviously inclined, which is related to the sunshine in the afternoon. Monitoring is used to analyze the cause and trend of deformation.',
            word_4_text:'Survey conclusions:\n' +
            '(1) It is necessary to use static level to monitor the uneven settlement of Goldoparin Temple in real time and analyze the regional settlement state.\n' +
            '(2) It is necessary to monitor the inclination of Goldoparin Temple and Ruishandu Temple by using inclination sensor in real time.\n' +
            '(3) It is necessary to monitor the cracks in the Gedao Palin Temple and Ruishan Du Temple in real time by using the crack gauge.',
            word_title3:'III. CONCLUSION OF MONITORING',
            b1_text1:'Table 3-1 Statistical Table of Monitoring Contents of the Golden Palin Temple',
            b1_text2:'Table 3-2 Statistical Table of Monitoring Content of Ruishan Duta',
            word_title4:'IV. Monitoring Data Achievements',
            word_title4_1:'Curve of cumulative deformation with time at each measuring point',
            p4_1:'Figure 4-1 Curve Chart of Cumulative Deformation with Time at Obliquity Monitoring Points of Golden Palin Temple',
            p4_2:'Figure 4-1 Curve Chart of Accumulated Deformation of Duta Inclination Monitoring Point in Ruishan with Time',
            p4_3:'Figure 4-1 Curve Chart of Accumulated Deformation of Crack Measurement Points at Golden Palin Temple Tower with Time',
            p4_4:'Figure 4-1 Curve Chart of Accumulated Deformation with Time at Crack Measuring Points of Duta Tower, Ruishan',
            p4_5:'Figure 4-1 Curve Chart of Accumulated Deformation of Differential Settlement Monitoring Points at Goldoparin Temple with Time',
            word_title5:'V. Layout of Surveying Points',
            p5_1:'Fig. 5-1 Sensor Layout of Golden Palin Temple',
            p5_2:'Fig. 5-2 Sensor Layout of Dufo Tower in Ruishan',
            word_A: 'Inclination sensor',
            word_C: 'Crack',
            word_D: 'Differential settlement',
            table1: 'Monitoring projects',
            table2: 'Max Devname',
            table3: 'Max Value',
            table4: 'Accumulative MaxDevname',
            table5: 'Accumulative MaxValue',
            table6: 'Change Rate',
            table7: 'Remarks',

        },

        alarm: 'Monitoring and Early Warning',
        number_: 'Number',
        why: 'Cause of alarm',
        handle: 'Alarm disposal',
        plan : 'Disposal plan',
        alarm_time: 'Alarm time',
        operation: 'Operation',
    },

}